### ISSUE TITLE
Linking Problems in Wrapper

### ISSUE THREAD

**Issue by shawnpringle** [gAndy50/Euraylib#1]
Hello Icy Viking!

I found an error in your code but the error inspired me to write https://github.com/shawnpringle/euphoriatools.  Using  one of these tools I found more.  Here are all the ones I found:

Could not load '+GetMonitorPhysicalHEight' from '../Euraylib/raylib.dll' in '../Euraylib/Euraylib.ew~' line 74, column 51.
Could not load '+StorageSaveValue' from '../Euraylib/raylib.dll' in '../Euraylib/Euraylib.ew~' line 736, column 55.
Could not load '+StorageLoadValue' from '../Euraylib/raylib.dll' in '../Euraylib/Euraylib.ew~' line 737, column 43.
Could not load '+GameGamepadButtonPressed' from '../Euraylib/raylib.dll' in '../Euraylib/Euraylib.ew~' line 814, column 50.
Could not load '+DrawingBoundingBox' from '../Euraylib/raylib.dll' in '../Euraylib/Euraylib.ew~' line 2630, column 42.
Could not load '+LoadText' from '../Euraylib/raylib.dll' in '../Euraylib/Euraylib.ew~' line 2746, column 47.
Could not load '+LoadWaveEx' from '../Euraylib/raylib.dll' in '../Euraylib/Euraylib.ew~' line 3007, column 37.
Could not load '+SetMusicLoopCOunt' from '../Euraylib/raylib.dll' in '../Euraylib/Euraylib.ew~' line 3170, column 44.
Could not load '+IsAudioBufferProcessed' from '../Euraylib/raylib.dll' in '../Euraylib/Euraylib.ew~' line 3259, column 49.
Could not load '+Vector2Multiply' from '../Euraylib/raylib.dll' in '../Euraylib/Euraylib.ew~' line 3424, column 54.
Could not load '+Vector3MultiplyV' from '../Euraylib/raylib.dll' in '../Euraylib/Euraylib.ew~' line 3512, column 55.
Could not load '+shimLoadTexture' from '../Euraylib/raylib.dll' in '../Euraylib/Euraylib.ew~' line 4508, column 51.
Could not load '+shimLoadTextureFromImage' from '../Euraylib/raylib.dll' in '../Euraylib/Euraylib.ew~' line 4509, column 51.
Could not load '+shimGetMouseRay' from '../Euraylib/raylib.dll' in '../Euraylib/Euraylib.ew~' line 4510, column 38.
Could not load '+shimGetWorldToScreen' from '../Euraylib/raylib.dll' in '../Euraylib/Euraylib.ew~' line 4511, column 43.

These are just spelling/case errors .  They should be easy to fix.

**Comment by gAndy50** [comment]
Hello Shawn,

Thanks for the heads up. I have fixed the typos.
